apiVersion: v1
kind: Service
metadata:
  name: vllm-gateway
  namespace: vllm
  labels:
    app.kubernetes.io/name: vllm-gateway
    app.kubernetes.io/part-of: vllm-on-azure
spec:
  type: ClusterIP
  ports:
    - port: 8080
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: vllm-gateway
---
apiVersion: v1
kind: Service
metadata:
  name: vllm-gateway-lb
  namespace: vllm
  labels:
    app.kubernetes.io/name: vllm-gateway
    app.kubernetes.io/part-of: vllm-on-azure
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: vllm-gateway
